# 本番環境用
FROM node:20.9.0-slim as build-stage

WORKDIR /app
COPY ./todoApp_frontend/package*.json ./
RUN npm install
COPY ./todoApp_frontend/ ./
RUN npm run build

FROM nginx:1.17.10-alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf
