@startuml db
entity users {
    ulid[PK]
    ---
    email
    name
    created_at
    updated_at
}

entity colors{
    id[UK]
    user_email[FK,UK]
    ---
    code
    created_at
    updated_at
}

entity projects{
    id[PK]
    ---
    name[UK]
    color_id[FK]
    memo
    user_email[FK,UK]
    created_at
    updated_at
}

entity events{
    id[PK]
    ---
    user_email[FK]
    title
    short_title
    project_id[FK]
    parent_event_id
    memo
    start
    end
    created_at
    updated_at
}

entity memo_templates{
    id[PK]
    ---
    name[UK]
    user_email[UK]
    template
    created_at
    updated_at
}
users --{ colors
users .{ projects
users .{ events
users .{ memo_templates
colors .{ projects
projects .{ events
@enduml