version: '3.6'
services:
  mysql:
    container_name: mysql
    build: ../docker/mysql
    image: todoapp_mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql
  backend:
    container_name: backend
    build: ./spring
    image: todoapp_backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    tty: true
    user: java
    volumes:
      - ../todoApp_backend:/home/java/srv:cached
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/java/.ssh
    working_dir: /home/java/srv
  frontend:
    container_name: frontend
    build: ./vue
    image: todoapp_frontend
    ports:
      - 9000:8080
    volumes:
      - ../todoApp_frontend:/home/node/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/node/.ssh
    working_dir: /home/node/app
    stdin_open: true
    tty: true
  redis:
    container_name: redis
    build: ./redis
    image: todoapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redisinsight:
    container_name: redisinsight
    build: ./redisinsight
    image: todoapp_redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis

volumes:
  mysql_db:
    driver: local
  redis-data:
