version: '3.6'
services:
  mysql-dev:
    container_name: mysql-dev
    build: ../docker/mysql
    image: todoapp_mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - mysql-db-dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 10s
  backend-dev:
    container_name: backend-dev
    build: ./spring
    image: todoapp_backend
    depends_on:
      mysql-dev:
        condition: service_healthy
    ports:
      - "8080:8080"
    tty: true
    user: java
    volumes:
      - ../todoApp_backend:/home/java/srv:cached
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/java/.ssh
    working_dir: /home/java/srv
  frontend-dev:
    container_name: frontend-dev
    build: ./vue
    image: todoapp_frontend
    ports:
      - 9000:8080
    volumes:
      - ../todoApp_frontend:/home/node/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/node/.ssh
    working_dir: /home/node/app
    stdin_open: true
    tty: true
  redis-dev:
    container_name: redis-dev
    build: ./redis
    image: todoapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
  redisinsight-dev:
    container_name: redisinsight-dev
    build: ./redisinsight
    image: todoapp_redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis-dev
  selenium-test:
    container_name: selenium-test
    build: ./selenium
    image: selenium_test
    user: seluser
    ports:
      - "4444:4444"
    volumes:
      - ../selenium_test:/home/seluser/selenium:cached
    working_dir: /home/seluser/selenium
    tty: true
    stdin_open: true

volumes:
  mysql-db-dev:
    driver: local
  redis-data-dev:
