openapi: 3.0.0
info:
  version: 1.0.0
  title: Project
paths:
  "/api/projects":
    get:
      tags:
        - "プロジェクト一覧取得API"
      summary: "プロジェクト一覧取得API"
      description: "ユーザーのプロジェクト一覧を返す。"
      parameters:
        - name: "sessionID"
          in: "header"
          description: "セッションID"
          required: true
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                  name:
                    type: "string"
                  color:
                    type: "string"
                  memo:
                    type: "string"
                  email:
                    type: "string"
                  createdAt:
                    type: "string"
                  updatedAt:
                    type: "string"
                example:
                  - id: "xxxxxxxx"
                    name: "project1"
                    color: "1"
                    memo: "memo"
                    email: "aaa@gmail.com"
                    createdAt: "2023-01-01T00:00:00.000+00:00"
                    updatedAt: "2023-01-01T00:00:00.000+00:00"
    post:
      tags:
        - "プロジェクト新規作成API"
      summary: "プロジェクト新規作成API"
      description: "プロジェクトを新規で作成する。"
      parameters:
        - name: "sessionID"
          in: "header"
          description: "セッションID"
          required: true
        - name: "name"
          in: "formData"
          description: "プロジェクト名"
          required: true
        - name: "memo"
          in: "formData"
          description: "メモ"
          required: true
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
