openapi: 3.0.0
info:
  version: 1.0.0
  title: MemoTemplate
paths:
  "/api/memo":
    get:
      tags:
        - "メモテンプレート一覧取得API"
      summary: "メモテンプレート一覧取得API"
      description: "ユーザーのメモテンプレート一覧を返す。"
      parameters:
        - name: "sessionID"
          in: "header"
          description: "セッションID"
          required: true
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                  name:
                    type: "string"
                  user_email:
                    type: "string"
                  template:
                    type: "string"
                  createdAt:
                    type: "string"
                  updatedAt:
                    type: "string"
                example:
                  - id: "xxxxxxxx"
                    name: "template1"
                    user_email: "aaa@gmail.com"
                    template: "# title"
                    created_at: "2023-01-01T00:00:00.000+00:00"
                    updated_at: "2023-01-01T00:00:00.000+00:00"
    post:
      tags:
        - "メモテンプレート新規作成API"
      summary: "メモテンプレート新規作成API"
      description: "メモテンプレートを新規で作成する。"
      parameters:
        - name: "sessionID"
          in: "header"
          description: "セッションID"
          required: true
        - name: "id"
          in: "formData"
          description: "テンプレートID"
          required: true
        - name: "name"
          in: "formData"
          description: "テンプレート名"
          required: true
        - name: "template"
          in: "formData"
          description: "テンプレート本文"
          required: true
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
    put:
      tags:
        - "メモテンプレート更新API"
      summary: "メモテンプレート更新API"
      description: "メモテンプレートを更新する。"
      parameters:
        - name: "sessionID"
          in: "header"
          description: "セッションID"
          required: true
        - name: "id"
          in: "formData"
          description: "テンプレートID"
          required: true
        - name: "name"
          in: "formData"
          description: "テンプレート名"
          required: true
        - name: "template"
          in: "formData"
          description: "テンプレート本文"
          required: true
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
