USE mysqldb;

CREATE TABLE IF NOT EXISTS users (
  ulid VARCHAR(26) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ulid`),
  UNIQUE KEY `UK1` (`email`)
);