@startuml event
title ログイン時のイベント取得
Front -> Front: ログイン
alt 新規セッション
    Front -> Front: ストアの中身をリセット
else
    Front -> Front: ストア内の最新のupdated_atを取得
end
Front -> Back: イベント取得用のGETリクエスト
note right:ストアの最新のupdated_atをパラメータに含む

Back -> DB: ログインユーザーの updated_at が最新のイベント取得query
activate DB
DB --> Back: ログインユーザーのイベントの最新のupdated_at
deactivate DB

Back -> GoogleCalendar: ログインユーザーのupdated_at以降のイベント一覧取得用のGETリクエスト
note left:storeかDBのうち古いほう、なければ初期値。
activate GoogleCalendar
GoogleCalendar --> Back: イベント一覧
deactivate GoogleCalendar

Back -> DB: イベント全件取得query
activate DB
DB --> Back: 対象ユーザーのイベント全件
deactivate DB

loop DBへ新規登録するイベントの件数
Back -> GoogleCalendar: DBへ新規登録するイベントの詳細習得用GETリクエスト
activate GoogleCalendar
GoogleCalendar --> Back: 各イベントの詳細
deactivate GoogleCalendar
end

Back -> DB: イベント登録
activate DB
DB --> Back: 登録完了
deactivate DB

Back --> Front: ログインユーザーのイベントを全件送信
Front -> Front: Storeに保存
@enduml